version: '3'

services: 

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    image: rfaguiar/nginx:prd
    container_name: nginx
    # entrypoint: dockerize -wait tcp://app:3000 -timeout 30s docker-entrypoint.sh nginx -g daemon off;
    networks: 
      - node-network
    ports: 
      - "8080:80"
    depends_on: 
       - app

  app:
    build: 
      context: ./nodejs/
      dockerfile: Dockerfile
    image: rfaguiar/nodejs-app:prd
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s docker-entrypoint.sh node index.js
    networks: 
      - node-network
    depends_on: 
       - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks: 
      - node-network

networks: 
  node-network:
    driver: bridge